# Generated by Django 3.2.5 on 2021-08-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musicians', '0001_initial'),
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='musicians',
            field=models.ManyToManyField(blank=True, related_name='albums', to='musicians.Musician'),
        ),
    ]
